# Generated by Django 4.0.3 on 2022-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusnotificationfile',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
