# Generated by Django 4.0.3 on 2022-05-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=0, max_length=200, null=0)),
                ('address', models.CharField(blank=0, max_length=200, null=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuthored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='customers',
            field=models.ManyToManyField(through='customer.DeviceAuthored', to='customer.customer'),
        ),
    ]
