# Generated by Django 4.0.3 on 2022-05-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_terms_customer_terms_accepted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='address',
        ),
    ]
